export interface Salle {
    idSalle: number;
    description: string;
    nombrePlace: number;
    forfait: number;
    numSalle: string;
  }
  
  export interface User {
    idUser: number;
    firstName: string;
    lastName: string;
    email: string;
    phoneNumber: string;
    role: string;
  }
  
  export interface Reservation {
    idReservation?: number;  // Optional because it's generated by the backend
    dateDebut: string 
    dateFin: string 
    duree: number;
    salle: Salle;
    user: User;
    dateDebutObj?: Date; 
    dateFinObj?: Date;
  }
  
  
  